### ISSUE TITLE
Clean up /workshops directory

### ISSUE THREAD

**Issue by paked** [hack-club/hackclub#484]
Currently we have a bunch of folders which likely shouldn't be in the `workshops` folder. I'm not sure how these managed to make the cut, but they add a certain amount of unnecessary clutter to the repository.

I (personally) would like to see the moving or removal of:

- [x] [frogger](https://github.com/hackedu/hackedu/tree/master/workshops/frogger/src) (being tracked in #469)
- [ ] [img](https://github.com/hackedu/hackedu/tree/master/workshops/img)
- [ ] [lib](https://github.com/hackedu/hackedu/tree/master/workshops/lib/twilio-basic)
- [x] [src](https://github.com/hackedu/hackedu/tree/master/workshops/src) (being tracked in #492)

cc: @hackedu/core

**Comment by zachlatta** [comment]
I'm totally down to clean up the workshops folder. `frogger` definitely shouldn't be there and `src` definitely shouldn't either.

`lib` contains our `twilio-basic` library that allows you to use Twilio in your browser and `img` contains images used in `workshops/README.md` and `workshops/workshop_details.md`. What if we delete `frogger` and `src` for now, then talk about cleaning up `workshop/workshop_details.md` as well?

**Comment by paked** [comment]
@zachlatta I'm still not a fan of having folders that *are not* workshops in the directory... Obviously we have to put the resources for `workshops/workshops_details.md` somewhere.

Maybe it would make sense to move `img` into `lib`?

Either way. What you have proposed sounds like a good start.

**Comment by zachlatta** [comment]
Err, I'm not sure about moving `img` into `lib` because the images aren't a library. I think it's okay to have directories like `img`, `lib`, and potentially `bin` as long as they're for associated files. Perhaps we could prefix them with an underscore to indicate that they're not workshops? So `_img`, `_lib`, and `_bin`?

**Comment by zachlatta** [comment]
Also, I submitted #492 to remove `workshops/src`.

**Comment by paked** [comment]
Ok. @zachlatta sounds good to me.

**Comment by zachlatta** [comment]
I'm going to close this issue for now because both `src` and `frogger` have been deleted. @paked please feel free to reopen if you'd like to discuss renaming `lib` and `img` to `_lib` and `_img` (or doing something else with them).
